### PR TITLE
Resized start button and Fixed start boss movement

### PR DESCRIPTION
**Pull request by coliny125**
The button is resized to the top of the screen and the boss now starts moving when start button is pressed.

### CODE REVIEW

**Review by chris-connoll-y — APPROVED** [review]
seems to work well

**Comment by Aarnonn** [comment]
LGTM! everything described worked well.

**Comment by mateensharifi** [comment]
Looks good and functions well!

**Review by Aarnonn — COMMENTED** [review]
oops i didn't approve it i just commented. I checked everything tho so dw.

**Pull request merged**
