### PR TITLE
tylers branch but in our heckin fork (aka main fork) and im reviewing in the thingy this makes sense ignore me

### PR DESCRIPTION
**Pull request by DidSomeoneSayBoba**
… fork

### CODE REVIEW

**Comment by DidSomeoneSayBoba** [comment]
Im reviewing the code and yes because i technically dont own this pull req

**Review by DonovanTyler — APPROVED** [review]
I kind of messed up stuff with Github, so Boba helped me make something that I could merge into main. That being said, I have tested my own code and can confirm that it works (this was originally meant to have Lia be the one reviewing my code, but since they already approved it informally, I'll sign off as one of the two reviews here).

**Review by louishess — APPROVED** [review]
changes functional and boss now shoots automatically, pull request is ready to be merged

**Review by DonovanTyler — APPROVED** [review]

**Review by solomonbaik — APPROVED** [review]
fantastic stuff!

**Pull request merged**
