### PR TITLE
fixed boss movement

### PR DESCRIPTION
**Pull request by ethanbrose**
made boss move left and right and change direction when appropriate

### CODE REVIEW

**Review by avadtran — APPROVED** [review]

**Comment by videozane** [comment]
-1 Not ready yet you need to resolve some conflicts in boss.js

**Comment by ethanbrose** [comment]
There were no conflicts when I submitted the pull request. Someone must've merged a pull request after I submitted mine.

**Comment by videozane** [comment]
> 

I can fix it give me a sec

**Comment by ethanbrose** [comment]
Thank you sir.

**Comment by videozane** [comment]
> Thank you sir.

Merge conflicts resolved. Signing off on this one

**Comment by ethanbrose** [comment]
Ok, I'm gonna merge now in case new conflicts arise.

**Pull request merged**
